### ISSUE TITLE
[Issue] "Clear Filter" always appear below the search bar

### ISSUE THREAD

**Issue by HASJ** [DakuTree/userscripts#5]
Firefox/Greasemonkey/2.0.7

I've tried fixing it on my own but all I was able to do with my non-existent coding skills is make "Apply Filter" appear along side "Clear Filter", below the bar.

![why](http://i.imgur.com/XJjoUd5.png)
![why!](http://i.imgur.com/0yUyWUB.png)

**Comment by HASJ** [comment]
Changed line 79
`.navbar input.stdinput {width: 350px; background-color: "+color1+"; color: "+color3+"; padding-bottom: 1px; border: 1px solid "+color1+";}\`

to
`.navbar input.stdinput {width: 330px; background-color: "+color1+"; color: "+color3+"; padding-bottom: 1px; border: 1px solid "+color1+";}\`

And that fixed it.

**Comment by DakuTree** [comment]
Fixed in 2.0.8 - ef95c56a16b000f621768dfe3cbea595bf8e13df

Problem seemed to be with browser specific styling, seemed to work fine with chrome :confused:
