### ISSUE TITLE
Old Header Links

### ISSUE THREAD

**Issue by DanInacio** [DakuTree/userscripts#6]
First of all, thank you for taking the time to create this. I like MAL the way it is and not the Facebook-y way it's trying to become.
Unfortunately, for some reason, it doesn't seem to work for me (nor for another user who posted on greasyfork).

**Comment by DakuTree** [comment]
I've just pushed out an update (1.0.4) which might fix your issue.
Try updating and see if it works now: https://greasyfork.org/en/scripts/16597

**Comment by DanInacio** [comment]
It did the trick. Thanks!
