### ISSUE TITLE
Compact search prompts security warning

### ISSUE THREAD

**Issue by netoxr2000** [DakuTree/userscripts#7]
Hi,
I'm not sure why but when I have compact search on I always get prompted by a security window. Also, not much bothersome, it won't let me turn on or off the different categories below the search bar. 

http://i64.tinypic.com/2d7bu4h.png

Regards,

**Comment by DakuTree** [comment]
What browser are you running to get the security window? I'm not seeing it on Chrome.
Edit: Looks like it's Firefox according to google..

**Comment by DakuTree** [comment]
2.0.15 should fix both issues. Hadn't noticed exhentai had moved over to https-only which was causing the security issue.

**Comment by netoxr2000** [comment]
Thanks, you actually fixed overnight.
